- name: Set up local workstation
  hosts: all
  roles:
    - role: base
      tags:
        - base
    - role: git
      tags:
        - git
    - role: zsh
      tags:
        - zsh
    - role: vim
      tags:
        - vim
    - role: tmux
      tags:
        - tmux
    - role: python
      tags:
        - python
    - role: terraform
      tags:
        - terraform
