- name: ensure "snapd" is installed
  package:
    name: snapd
  become: yes
  become_user: root
  become_method: sudo

# Install a snap with classic confinement
- name: Install "spotify" with option --classic
  snap:
    name: spotify
    classic: yes

# Install a snap with classic confinement
- name: Install "slack" with option --classic
  snap:
    name: slack
    classic: yes

- name: Install "rocketchat-desktop" with option
  snap:
    name: rocketchat-desktop


