- name: Install python
  package: name=python state=present
  become_user: root
  become: true
  become_method: sudo

- name: Install python3
  package: name=python3 state=present
  become_user: root
  become: true
  become_method: sudo
