font=monospace:size=12

[main]
#shell=/usr/bin/fish

#include=/home/galvaro/.config/foot/tokyonight-night
#include=/usr/share/foot/themes/nordiq
include=/usr/share/foot/themes/gruvbox-dark

[colors]
alpha=0.95

[key-bindings]
pipe-scrollback=[sh -c 'tmp=$(mktemp); cat >"$tmp"; foot -e nvim "$tmp"'] Control+Shift+h
