- name: Install zsh
  package: name=zsh state=present
  become: yes
  become_user: root
  become_method: sudo

- name: Check for oh-my-zsh installation
  stat: "path=~/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh
  raw: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
  when: not oh_my_zsh_stat.stat.exists

- name: Copy .zshrc
  copy:
    src: "zshrc"
    dest: "~/.zshrc"

- name: Create folder .zsh
  file:
    path: "~/.zsh"
    state: directory
    mode: '0755'

- name: Copy .zsh/ folder
  copy:
    src: "zsh/"
    dest: "~/.zsh"

- name: Change shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
  become_user: root
  become_method: sudo

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  when: oh_my_zsh_stat.stat.exists
