- name: Download terraform ZIP
  get_url:
      url: https://releases.hashicorp.com/terraform/{{version}}/terraform_{{version}}_linux_amd64.zip
      dest: /tmp/terraform.zip
      mode: '0440'

- name: Extract terraform.zip into /usr/local/bin/
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
  become_method: sudo
  become_user: root
  become: yes

