- name: Install i3wmn
  package:
    name:
      - i3
      - i3status
      - i3lock
      - network-manager-applet
      - pavucontrol
      - google-roboto-fonts
      - rxvt-unicode
      - fontawesome-fonts
    state: present
  become_user: root
  become: true
  become_method: sudo

- name: Create config folder
  file:
    path: ~/.config/i3/
    state: directory

- name: Copy .config/i3/
  copy:
    src: "config"
    dest: "~/.config/i3/config"

- name: i3status
  copy:
    src: i3status.conf
    dest: "~/.config/i3/i3status.conf"

#
# Terminal
#

- name: Copy .Xdefaults
  copy:
    src: "Xdefaults"
    dest: "~/.Xdefaults"



- name: Create urxvt config folder
  file:
    path: ~/.urxvt/ext
    state: directory

- name: Copy .urxvt/ext/font-size
  copy:
    src: "font-size"
    dest: "~/.urxvt/ext/font-size"


