- name: Install tmux
  package: name=tmux state=present
  become_user: root
  become: true
  become_method: sudo

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link

