- name: Install foot terminal
  package:
    name:
    - foot
    state: present
  become_user: root
  become: true
  become_method: sudo

- name: Create config folder
  file:
    path: ~/.config/foot
    state: directory

- name: Copy config
  copy:
    src: "foot.ini"
    dest: "~/.config/foot/"


