- name: ensure a list of packages installed
  package:
    name: "{{ packages }}"
  become: yes
  become_user: root
  become_method: sudo
  vars:
    packages:
    - wget
    - curl
    - unzip
    - whois
    - jq
    - docker
    - nmap
    - xclip

- name: ensure a list of Python3 packages to be installed
  pip:
    name: "{{ packages }}"
    executable: pip3
  become: yes
  become_user: root
  become_method: sudo
  vars:
    packages:
    - python-swiftclient
    - python-keystoneclient
    - yq
    - asciinema
