- name: Install vim
  package: name=vim state=present
  become_user: root
  become: true
  become_method: sudo

- name: Symlink .vimrc
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/vimrc"
    dest: "{{dotfiles_user_home}}/.vimrc"
    state: link

