- name: Install vim
  package:
    name:
    - neovim
    state: present
  become_user: root
  become: true
  become_method: sudo

- name: Create config folder
  file:
    path: ~/.vim/
    state: directory

- name: Copy .vimrc
  copy:
    src: "vimrc"
    dest: "~/.vim/vimrc"


